version: 2.1

orbs:
  node: circleci/node@5.0.2
  codecov: codecov/codecov@3.1.1

jobs:
  tests:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.13"
      - run:
          name: Show node version
          command: |
            node --version
            yarn --version
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run lint check
          command: yarn lint
      - run:
          name: Run unit tests with coverage
          command: yarn cover
      - codecov/upload:
          file: coverage/*.json
  versioning:
    docker:
      - image: cimg/node:16.15.1
    steps:
      - checkout
      - run:
          name: check package version
          command: node scripts/check-version.js rhebecaabreu gestao-de-frotas-lp
  chromatic:
    docker:
      - image: cimg/node:16.15.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - run: yarn chromatic --project-token=${CHROMATIC_TOKEN}

workflows:
  ci:
    jobs:
      - chromatic
      - tests
      - versioning:
          filters:
            branches:
              ignore: main
            tags:
              ignore: /.*/
