version: 2.1

orbs:
  node: circleci/node@5.0.2
  codecov: codecov/codecov@3.1.1

jobs:
  tests:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.13"
      - run: node --version
      - run: yarn --version
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint
      - run: yarn cover
      - codecov/upload:
          file: coverage/*.json
  versioning:
    docker:
      - image: circleci/node@5.0.2
    steps:
      - checkout
      - run:
          name: check package version
          command: node scripts/check-version.js rhebecaabreu gestao-de-frotas-lp
workflows:
  ci:
    jobs:
      - tests
      - versioning:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
